all:
	vcs -full64 -sverilog +v2k -R -nc -debug_acc+pp+fsdb -nospecify -fsdb -f ./toy_bus_DWrap_network_toy_bus/toy_bus.f +lint=PCWM +lint=TFIPC-L -LDFLAGS -rdynamic -P ${NOVAS_HOME}/share/PLI/VCS/LINUX64/novas.tab ${NOVAS_HOME}/share/PLI/VCS/LINUX64/pli.a
